# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a923ae81adbbf600d9e0275bb2504ed247dc288adcc672f2d1bf971d9a8a70077d41d1a8f8675338646ca87f97ad198a1184146965d77f685fb2877c7ae881f

test:
  secret_key_base: 38b5705fb7a212c2a6a7765b8a8d3773ddb074d755507747e45dd6d322636a37c08232293b82492c00840e1620fe008d44cde1fc8b091f770e14659619783170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
